### ISSUE TITLE
Installation Does Not Work As Documented

### ISSUE THREAD

**Issue by ebrightfield** [openlilylib/oll-core#48]
To reproduce, follow instructions as stated in documentation, and execute a that looks like:
```
\include "oll-core/package.ily"
```
with the command 

```
lilypond -I <path-to-oll-lib-folder> <filename>
```

Yields the following output:

```
Parsing...
./oll-lib/oll-core/internal/init.ily:47:2: error: GUILE signaled an error for the expression beginning here
#
 (use-modules (oll-core internal tools))
no code for module (oll-core internal tools)
./oll-lib/oll-core/internal/init.ily:48:2: error: GUILE signaled an error for the expression beginning here
#
 (use-modules (oll-core internal grob-tools))
no code for module (oll-core internal grob-tools)
./oll-lib/oll-core/internal/init.ily:49:2: error: GUILE signaled an error for the expression beginning here
#
 (use-modules (oll-core internal control))
no code for module (oll-core internal control)
./oll-lib/oll-core/internal/init.ily:52:2: error: GUILE signaled an error for the expression beginning here
#
 (use-modules (oll-core internal lilypond-version-predicates))
no code for module (oll-core internal lilypond-version-predicates)
./oll-lib/oll-core/internal/init.ily:55:2: error: GUILE signaled an error for the expression beginning here
#
 (use-modules (oll-core internal alist-access))
no code for module (oll-core internal alist-access)
./oll-lib/oll-core/internal/options.ily:378:1: error: unknown escaped string: `\newAtree'

\newAtree oll-options
./oll-lib/oll-core/internal/options.ily:378:11: error: syntax error, unexpected SYMBOL, expecting ',' or '.' or '='
\newAtree 
          oll-options
./oll-lib/oll-core/internal/options.ily:389:4: In expression (setAtree (quote oll-options) opt-path ...):
./oll-lib/oll-core/internal/options.ily:389:4: Unbound variable: setAtree

shell returned 1
```

Something weird with the pathing, but I can't figure it out. I'm fairly sure it's not user error in the form of bad path in the `-I` flag, because I otherwise wouldn't be seeing errors from `init.ily`.

**Comment by uliska** [comment]
I can confirm your assumption about user error and `init.ily`.

One thing that comes to mind is: is `<filename>` an absolute or relative path? And if the latter, is it a file in the current working directory or something like `relative/path/to/file.ly`?

And, just to be complete: What operating system do you use?

**Comment by uliska** [comment]
I've tried to replicate your example, and although the error is not identical it seems close enough.

I get similar error messages when specifying the path to openLilyLib's root folder as a relative path from the current working dir, but not when it is given as an absolute path (this is on Linux).

I can very well imagine that this is the issue, and that an include path should be given as an absolute path.

@ebrightfield could you please check this. if it proves to be the issue I'll update the instructions accordingly.

**Comment by ebrightfield** [comment]
Relative pathing was indeed the issue. When I changed the `-I` flag's path to an absolute path, it worked. 

I am running on Linux on x86, Manjaro 5.6.15-1.

**Comment by uliska** [comment]
I was not aware of that because Frescobaldi alwaya creates absolute paths.

I'll update the wiki page, thank youbfor reporting.

**Comment by uliska** [comment]
Fixed
