### ISSUE TITLE
Review tree-merge!

### ISSUE THREAD

**Issue by uliska** [openlilylib/oll-core#6]
What does the `(proc <procedure>)` in `tree-merge!` do?

**Comment by jpvoigt** [comment]
The idea is, to merge two trees and *not* override the values of one 
tree with the other. There must have been a use case ...
The procedure shall return a resulting value, if the node in both trees 
have values. This is not tested in the current version. I will do so and 
implement a procedure to just override one with the other as a special 
case of merge.
For example: If there are contexct-mods in the trees, they can be joined 
into one.

But still, I have to review this ancient code ;-)


Am 15.03.2016 um 18:34 schrieb Urs Liska:

**Comment by uliska** [comment]
OK, thanks for the explanation. Then I'll simply leave that alone

**Comment by jpvoigt** [comment]
Well, my explanation was not OK:
`tree-merge!` "merges" a value with the value at path.
So if there is a context-mod at path my/context/mod and you call `(tree-merge! tree '(my context mod) (lambda (m1 m2) #{ \with { $m1 $m2 } #}) #{ \with {} #})` the two context-mods will be combined into one and stored under the designated path.
I included an example in the current PR
